import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const fontPath = path.join(__dirname, '..', 'public', 'fonts', 'BlissProRegular.otf');
const fontBuffer = fs.readFileSync(fontPath);
const base64 = fontBuffer.toString('base64');

// Write the base64 string to a file
const outputPath = path.join(__dirname, '..', 'src', 'utils', 'fonts', 'blissPro.ts');
const fileContent = `// Generated by scripts/generateFontBase64.mjs
export const blissProBase64 = "${base64}";
`;

fs.writeFileSync(outputPath, fileContent);
console.log('Font base64 string has been written to src/utils/fonts/blissPro.ts'); 